//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaPP.Units {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Units {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Units() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AquaPP.Units.Units", typeof(Units).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³/s.
        /// </summary>
        internal static string Symbol_FlowRate_CubicMeterPerSecond {
            get {
                return ResourceManager.GetString("Symbol_FlowRate_CubicMeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal/min.
        /// </summary>
        internal static string Symbol_FlowRate_GallonPerMinute {
            get {
                return ResourceManager.GetString("Symbol_FlowRate_GallonPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string Symbol_Length_Foot {
            get {
                return ResourceManager.GetString("Symbol_Length_Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Symbol_Length_Meter {
            get {
                return ResourceManager.GetString("Symbol_Length_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string Symbol_Mass_Kilogram {
            get {
                return ResourceManager.GetString("Symbol_Mass_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string Symbol_Mass_Pound {
            get {
                return ResourceManager.GetString("Symbol_Mass_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        internal static string Symbol_Pressure_Pascal {
            get {
                return ResourceManager.GetString("Symbol_Pressure_Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psi.
        /// </summary>
        internal static string Symbol_Pressure_Psi {
            get {
                return ResourceManager.GetString("Symbol_Pressure_Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Symbol_Temperature_Celsius {
            get {
                return ResourceManager.GetString("Symbol_Temperature_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string Symbol_Temperature_Fahrenheit {
            get {
                return ResourceManager.GetString("Symbol_Temperature_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³.
        /// </summary>
        internal static string Symbol_Volume_CubicMeter {
            get {
                return ResourceManager.GetString("Symbol_Volume_CubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        internal static string Symbol_Volume_Gallon {
            get {
                return ResourceManager.GetString("Symbol_Volume_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic meter per second.
        /// </summary>
        internal static string Unit_FlowRate_CubicMeterPerSecond {
            get {
                return ResourceManager.GetString("Unit_FlowRate_CubicMeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon per minute.
        /// </summary>
        internal static string Unit_FlowRate_GallonPerMinute {
            get {
                return ResourceManager.GetString("Unit_FlowRate_GallonPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foot.
        /// </summary>
        internal static string Unit_Length_Foot {
            get {
                return ResourceManager.GetString("Unit_Length_Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        internal static string Unit_Length_Meter {
            get {
                return ResourceManager.GetString("Unit_Length_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogram.
        /// </summary>
        internal static string Unit_Mass_Kilogram {
            get {
                return ResourceManager.GetString("Unit_Mass_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pound.
        /// </summary>
        internal static string Unit_Mass_Pound {
            get {
                return ResourceManager.GetString("Unit_Mass_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pascal.
        /// </summary>
        internal static string Unit_Pressure_Pascal {
            get {
                return ResourceManager.GetString("Unit_Pressure_Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psi.
        /// </summary>
        internal static string Unit_Pressure_Psi {
            get {
                return ResourceManager.GetString("Unit_Pressure_Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Unit_Temperature_Celsius {
            get {
                return ResourceManager.GetString("Unit_Temperature_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Unit_Temperature_Fahrenheit {
            get {
                return ResourceManager.GetString("Unit_Temperature_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic meter.
        /// </summary>
        internal static string Unit_Volume_CubicMeter {
            get {
                return ResourceManager.GetString("Unit_Volume_CubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon.
        /// </summary>
        internal static string Unit_Volume_Gallon {
            get {
                return ResourceManager.GetString("Unit_Volume_Gallon", resourceCulture);
            }
        }
    }
}
